const galerieOfficielle = [
  {
    titre: "Défilé militaire et civil",
    date: "30 Août",
    photos: [
      { src: "/Defile1.jpg" }, { src: "/Defile2.jpg" }, { src: "/Defile3.jpg" }, { src: "/Defile4.jpg" },
      { src: "/Defile5.jpg" }, { src: "/Defile6.jpg" }, { src: "/Defile7.jpg" }, { src: "/Defile8.jpg" },
      { src: "/Defile9.jpg" }, { src: "/Defile10.jpg" }, { src: "/Defile11.jpg" }, { src: "/Defile12.jpg" },
      { src: "/Defile13.jpg" }, { src: "/Defile14.jpg" }, { src: "/Defile15.jpg" }, { src: "/Defile16.jpg" },
      { src: "/Defile17.jpg" }, { src: "/Defile18.jpg" }, { src: "/Defile19.jpg" }, { src: "/Defile20.jpg" },
      { src: "/Defile21.jpg" }, { src: "/Defile22.jpg" }, { src: "/Defile23.jpg" }, { src: "/Defile24.jpg" },
      { src: "/Defile25.jpg" }, { src: "/Defile26.jpg" }, { src: "/Defile27.jpg" }, { src: "/Defile28.jpg" },
      { src: "/Defile29.jpg" }, { src: "/Defile30.jpg" }, { src: "/Defile31.jpg" }, { src: "/Defile32.jpg" },
      { src: "/Defile33.jpg" }, { src: "/Defile34.jpg" }, { src: "/Defile35.jpg" }, { src: "/Defile36.jpg" },
      { src: "/Defile37.jpg" }, { src: "/Defile38.jpg" },
    ],
  },
  {
    titre: "Arrivée du Président en Ogooué-Ivindo",
    date: "27 Août",
    photos: [
      { src: "/Arrivée1.jpg" }, { src: "/Arrivée2.jpg" }, { src: "/Arrivée3.jpg" }, { src: "/Arrivée4.jpg" },
      { src: "/Arrivée5.jpg" }, { src: "/Arrivée6.jpg" }, { src: "/Arrivée7.jpg" }, { src: "/Arrivée8.jpg" },
      { src: "/Arrivée9.jpg" }, { src: "/Arrivée10.jpg" }, { src: "/Arrivée11.jpg" }, { src: "/Arrivée12.jpg" },
      { src: "/Arrivée13.jpg" }, { src: "/Arrivée14.jpg" }, { src: "/Arrivée15.jpg" }, { src: "/Arrivée16.jpg" },
      { src: "/Arrivée17.jpg" }, { src: "/Arrivée18.jpg" }, { src: "/Arrivée19.jpg" }, { src: "/Arrivée20.jpg" },
      { src: "/Arrivée21.jpg" }, { src: "/Arrivée22.jpg" },
    ],
  },
  {
    titre: "Caravane médicale",
    date: "24 Août",
    photos: [
      { src: "/Caravane1.jpg" }, { src: "/Caravane2.jpg" }, { src: "/Caravane3.jpg" }, { src: "/Caravane4.jpg" },
      { src: "/Caravane5.jpg" }, { src: "/Caravane6.jpg" }, { src: "/Caravane7.jpg" }, { src: "/Caravane8.jpg" },
    ],
  },
  {
    titre: "Centrale d'achat",
    date: "24 Août",
    photos: [
      { src: "/Centrale1.jpg" }, { src: "/Centrale2.jpg" }, { src: "/Centrale3.jpg" },
      { src: "/Centrale4.jpg" }, { src: "/Centrale5.jpg" }, { src: "/Centrale6.jpg" },
      { src: "/Centrale7.jpg" }, { src: "/Centrale8.jpg" }, { src: "/Centrale9.jpg" },
    ],
  },
  {
    titre: "Opération ville propre",
    date: "23 Août",
    photos: [
      { src: "/propre1.jpg" }, { src: "/propre2.jpg" }, { src: "/propre3.jpg" }, { src: "/propre4.jpg" },
      { src: "/propre5.jpg" }, { src: "/propre6.jpg" }, { src: "/propre7.jpg" }, { src: "/propre8.jpg" },
      { src: "/propre9.jpg" }, { src: "/propre10.jpg" }, { src: "/propre11.jpg" }, { src: "/propre12.jpg" },
      { src: "/propre13.jpg" }, { src: "/propre14.jpg" }, { src: "/propre15.jpg" }, { src: "/propre16.jpg" },
      { src: "/propre17.jpg" }, { src: "/propre18.jpg" }, { src: "/propre19.jpg" }, { src: "/propre20.jpg" },
      { src: "/propre21.jpg" }, { src: "/propre22.jpg" }, { src: "/propre23.jpg" }, { src: "/propre24.jpg" },
      { src: "/propre25.jpg" }, { src: "/propre26.jpg" }, { src: "/propre27.jpg" }, { src: "/propre28.jpg" },
      { src: "/propre29.jpg" }, { src: "/propre30.jpg" }, { src: "/propre31.jpg" }, { src: "/propre32.jpg" },
    ],
  },
  {
    titre: "Séminaire à l'intention des élus locaux",
    date: "20-21 Août",
    photos: [
      { src: "/seminaire-1.jpeg" },
      { src: "/seminaire-2.jpeg" },
      { src: "/seminaire-3.jpeg" },
      { src: "/seminaire-4.jpeg" },
      { src: "/seminaire-5.jpeg" },
      { src: "/seminaire-6.jpeg" },
      { src: "/seminaire-7.jpeg" },
      { src: "/seminaire-8.jpeg" },
      { src: "/seminaire-9.jpeg" },
      { src: "/seminaire-10.jpeg" },
      { src: "/seminaire-11.jpeg" },
      { src: "/seminaire-12.jpeg" },
      { src: "/seminaire-13.jpeg" },
    ],
  },
  { titre: "Caravane médicale", date: "24-26 Août", photos: [] },
  { titre: "Ouverture du village Ogivin", date: "24-29 Août", photos: [] },
  { titre: "Méga marché de la Centrale d'Achat", date: "24-26 Août", photos: [] },
  { titre: "Colloque sur l'Ogooué-Ivindo", date: "25-26 Août", photos: [] },
  { titre: "Cross de la Libération", date: "26 Août", photos: [] },
  { titre: "Forum économique de l'Ogooué-Ivindo", date: "27 Août", photos: [] },
  {
    titre: "Arrivée du Président en Ogooué-Ivindo",
    date: "27 Août",
    photos: [
      { src: "/Arrivée1.jpg" }, { src: "/Arrivée2.jpg" }, { src: "/Arrivée3.jpg" }, { src: "/Arrivée4.jpg" },
      { src: "/Arrivée5.jpg" }, { src: "/Arrivée6.jpg" }, { src: "/Arrivée7.jpg" }, { src: "/Arrivée8.jpg" },
      { src: "/Arrivée9.jpg" }, { src: "/Arrivée10.jpg" }, { src: "/Arrivée11.jpg" }, { src: "/Arrivée12.jpg" },
      { src: "/Arrivée13.jpg" }, { src: "/Arrivée14.jpg" }, { src: "/Arrivée15.jpg" }, { src: "/Arrivée16.jpg" },
      { src: "/Arrivée17.jpg" }, { src: "/Arrivée18.jpg" }, { src: "/Arrivée19.jpg" }, { src: "/Arrivée20.jpg" },
      { src: "/Arrivée21.jpg" }, { src: "/Arrivée22.jpg" },
    ],
  },
  { titre: "Inauguration du Mausolée Emmanuel Issoze Ngondet", date: "28 Août", photos: [] },
  { titre: "Découverte des chutes de Kongou", date: "28 Août", photos: [] },
  { titre: "Dîner offert par les Parlementaires", date: "28 Août", photos: [] },
  { titre: "Exposition des FDS & Journée de la Défense", date: "29 Août", photos: [] },
  { titre: "Distribution des kits scolaires", date: "29 Août", photos: [] },
  { titre: "Finale de football et de boxe", date: "29 Août", photos: [] },
  { titre: "Dîner offert par la Présidente du Sénat", date: "29 Août", photos: [] },
  { titre: "Cérémonie de décorations", date: "30 Août", photos: [] },
  { titre: "Défilé militaire et civil", date: "30 Août", photos: [] },
  { titre: "Pose de la première pierre - Fortescue Iron", date: "30 Août", photos: [] },
  { titre: "Concert de la Libération", date: "30 Août", photos: [] },
  { titre: "Dîner offert par le Couple Présidentiel", date: "30 Août", photos: [] },
  { titre: "Retour des délégations", date: "31 Août", photos: [] },
];

export default galerieOfficielle;
