const quizQuestions = [
  // HISTOIRE
  { theme: "Histoire", difficulte: "facile", question: "En quelle année la ville de Makokou a-t-elle été fondée ?", options: ["1908", "1875", "1936", "1960"], correct: 0, explication: "Makokou a été fondée en 1908, marquant le début de son développement en tant que centre administratif de la région." },
  { theme: "Histoire", difficulte: "moyen", question: "Quel événement marquant a eu lieu à Makokou en 1908 ?", options: ["Un soulèvement des populations Bakota", "La signature d'un traité", "Une épidémie", "Un tremblement de terre"], correct: 0, explication: "En 1908, un soulèvement des populations Bakota a marqué l'histoire de la région face à l'administration coloniale." },
  { theme: "Histoire", difficulte: "difficile", question: "Quels explorateurs ont remonté l'Ogooué jusqu'à l'Ivindo en 1873-1874 ?", options: ["Le Marquis de Compiègne et Alfred Marche", "David Livingstone", "Pierre de Brazza seul", "Henry Morton Stanley"], correct: 0, explication: "Le Marquis de Compiègne et Alfred Marche furent parmi les premiers explorateurs européens à remonter l'Ogooué jusqu'à l'Ivindo, en 1873-1874." },
  { theme: "Histoire", difficulte: "moyen", question: "En quelle année Booué est-elle devenue un poste militaire ?", options: ["1887", "1908", "1914", "1936"], correct: 0, explication: "Booué est devenue un poste militaire dès 1887, une étape clé de l'installation administrative de la région." },
  { theme: "Histoire", difficulte: "difficile", question: "En quelle année la ville de Mékambo a-t-elle été créée ?", options: ["1914", "1900", "1936", "1960"], correct: 0, explication: "La ville de Mékambo a été créée en 1914." },

  // BIODIVERSITÉ
  { theme: "Biodiversité", difficulte: "facile", question: "Quel primate emblématique peuple en grand nombre le Parc national de Lopé ?", options: ["Le mandrill", "Le colobe", "Le potto", "Le galago"], correct: 0, explication: "Le Parc national de la Lopé abrite l'une des plus importantes populations de mandrills au monde." },
  { theme: "Biodiversité", difficulte: "difficile", question: "Combien d'espèces d'oiseaux sont recensées au Parc national de Lopé (sur 700 au Gabon) ?", options: ["412", "150", "600", "250"], correct: 0, explication: "Le Parc de la Lopé recense environ 412 espèces d'oiseaux, sur les quelque 700 que compte le Gabon." },
  { theme: "Biodiversité", difficulte: "moyen", question: "Quelle réserve de biosphère se situe le long de l'Ivindo, près de Makokou ?", options: ["Ipassa-Makokou", "Lopé-Okanda", "Minkébé", "Moukalaba"], correct: 0, explication: "La réserve de biosphère d'Ipassa-Makokou, le long de l'Ivindo, est un site de recherche scientifique reconnu par l'UNESCO." },
  { theme: "Biodiversité", difficulte: "moyen", question: "Quel animal peut-on observer en toute sécurité dans la clairière (baï) de Langoué ?", options: ["Le sitatunga", "Le lion", "Le zèbre", "Le rhinocéros"], correct: 0, explication: "La clairière de Langoué, dans le Parc de l'Ivindo, permet d'observer notamment le sitatunga, une antilope semi-aquatique." },
  { theme: "Biodiversité", difficulte: "facile", question: "Quel parc abrite des éléphants de forêt n'ayant jamais eu de contact avec l'homme, ainsi que de belles chutes ?", options: ["Le Parc national de l'Ivindo", "Le Parc de la Lopé", "Le Parc de Minkébé", "Le Parc de Moukalaba"], correct: 0, explication: "Le Parc national de l'Ivindo abrite des éléphants de forêt vivant loin de toute présence humaine, ainsi que les chutes de Kongou." },

  // TOURISME
  { theme: "Tourisme", difficulte: "facile", question: "Les célèbres chutes de Kongou se trouvent sur quelle rivière ?", options: ["L'Ivindo", "L'Ogooué", "La Ngounié", "La Sangha"], correct: 0, explication: "Les chutes de Kongou, sur la rivière Ivindo, comptent parmi les plus impressionnantes d'Afrique centrale." },
  { theme: "Tourisme", difficulte: "facile", question: "Quel lac pittoresque, entouré de végétation luxuriante, attire les visiteurs près de Makokou ?", options: ["Le lac Tchimbélé", "Le lac Onangué", "Le lac Azingo", "Le lac Ezanga"], correct: 0, explication: "Le lac Tchimbélé, entouré de forêt, est apprécié pour ses paysages naturels." },
  { theme: "Tourisme", difficulte: "facile", question: "Quelle activité nautique populaire peut-on pratiquer sur l'Ivindo à Makokou ?", options: ["Le kayak", "Le ski nautique", "La plongée", "La voile"], correct: 0, explication: "Le kayak est une activité nautique appréciée sur l'Ivindo, pour découvrir les paysages de la rivière." },
  { theme: "Tourisme", difficulte: "moyen", question: "Quel village situé à ~15 km de Makokou est réputé pour son artisanat et ses traditions ?", options: ["Le village Sifa", "Le village Ipassa", "Le village Booué", "Le village Ovan"], correct: 0, explication: "Le village Sifa, à environ 15 km de Makokou, est réputé pour son artisanat traditionnel." },
  { theme: "Tourisme", difficulte: "difficile", question: "Combien de temps de navigation faut-il environ pour atteindre les chutes de Kongou ?", options: ["3 à 4 heures", "30 minutes", "8 à 10 heures", "1 journée complète"], correct: 0, explication: "Il faut compter environ 3 à 4 heures de navigation pour atteindre les chutes de Kongou depuis Makokou." },

  // RICHESSES NATURELLES
  { theme: "Richesses naturelles", difficulte: "facile", question: "Quel minerai précieux se trouve au Mont Bélinga ?", options: ["Le fer", "L'or", "Le cuivre", "Le diamant"], correct: 0, explication: "Le Mont Bélinga renferme d'importants gisements de fer, l'une des grandes richesses minières de la province." },
  { theme: "Richesses naturelles", difficulte: "facile", question: "Quels deux cours d'eau donnent son nom à la province ?", options: ["L'Ogooué et l'Ivindo", "La Ngounié et l'Ogooué", "L'Ivindo et la Sangha", "L'Ogooué et le Komo"], correct: 0, explication: "La province tire son nom des deux cours d'eau qui la traversent : l'Ogooué et l'Ivindo." },
  { theme: "Richesses naturelles", difficulte: "moyen", question: "Quelle est la superficie de la province de l'Ogooué-Ivindo ?", options: ["46 075 km²", "20 000 km²", "65 000 km²", "32 000 km²"], correct: 0, explication: "L'Ogooué-Ivindo s'étend sur environ 46 075 km², l'une des plus vastes provinces du Gabon." },
  { theme: "Richesses naturelles", difficulte: "difficile", question: "Environ quel pourcentage du territoire de la province est couvert par des parcs nationaux ?", options: ["~21%", "~5%", "~50%", "~35%"], correct: 0, explication: "Environ 21% du territoire de la province est couvert par des parcs nationaux, reflet de sa richesse en biodiversité." },
  { theme: "Richesses naturelles", difficulte: "moyen", question: "Quel pays voisin borde l'Ogooué-Ivindo au sud-est ?", options: ["La République du Congo", "Le Cameroun", "La Guinée équatoriale", "La République centrafricaine"], correct: 0, explication: "La République du Congo borde l'Ogooué-Ivindo au sud-est." },

  // CULTURE & PEUPLES
  { theme: "Culture", difficulte: "moyen", question: "Comment appelle-t-on le culte des ancêtres pratiqué par les Kota, associé aux figures reliquaires ?", options: ["Le bwété", "Le bwiti", "Le ndjembé", "Le mvett"], correct: 0, explication: "Le bwété est le culte des ancêtres kota, centré sur la conservation et la protection des reliques familiales." },
  { theme: "Culture", difficulte: "facile", question: "Les figures reliquaires kota (mbulu-ngulu) servaient à protéger quoi ?", options: ["Les ossements des ancêtres", "Les récoltes", "Les habitations", "Le bétail"], correct: 0, explication: "Les mbulu-ngulu étaient placées sur des paniers contenant les ossements des ancêtres, pour les protéger symboliquement." },
  { theme: "Culture", difficulte: "difficile", question: "Selon l'étude de Louis Perrois, combien de styles différents de figures reliquaires kota a-t-on pu identifier ?", options: ["15 styles", "5 styles", "30 styles", "3 styles"], correct: 0, explication: "L'ethnologue Louis Perrois a recensé environ 15 styles différents de figures reliquaires kota selon les sous-groupes et régions." },
  { theme: "Culture", difficulte: "moyen", question: "En quelle matière les figures reliquaires kota sont-elles principalement recouvertes ?", options: ["Laiton et cuivre martelés", "Or", "Perles de verre", "Tissu tissé"], correct: 0, explication: "Les figures reliquaires kota sont sculptées dans le bois puis recouvertes de laiton et de cuivre martelés." },
  { theme: "Culture", difficulte: "facile", question: "Les Mahongwé, qui vivent dans l'Ogooué-Ivindo, appartiennent à quel grand groupe ethnolinguistique ?", options: ["Le groupe Kota", "Le groupe Fang", "Le groupe Myéné", "Le groupe Punu"], correct: 0, explication: "Les Mahongwé font partie du grand groupe ethnolinguistique kota, tout en ayant leur propre langue et leurs propres traditions." },
  { theme: "Culture", difficulte: "difficile", question: "D'où proviendraient historiquement les ancêtres des Kota, selon les traditions orales ?", options: ["Du nord-est, en suivant la vallée de l'Ivindo", "D'Afrique de l'Ouest", "Du littoral atlantique", "D'Afrique du Nord"], correct: 0, explication: "Selon les traditions orales et les travaux de Perrois, les ancêtres kota seraient venus du nord-est (zone Cameroun/Congo) en suivant la vallée de l'Ivindo." },
  { theme: "Culture", difficulte: "moyen", question: "Parmi ces peuples, lesquels sont restés dans l'Ogooué-Ivindo alors que d'autres groupes kota poursuivaient leur migration vers le sud ?", options: ["Les Mahongwé et les Kwélé", "Les Punu et les Vili", "Les Myéné", "Les Téké"], correct: 0, explication: "Contrairement à d'autres groupes kota partis plus au sud, les Mahongwé et les Kwélé sont restés dans la région de l'Ogooué-Ivindo." },
  { theme: "Culture", difficulte: "moyen", question: "Chez les Kota, à quelle période de l'année se déroulent traditionnellement les grandes cérémonies de circoncision ?", options: ["La saison sèche (juin à septembre)", "La saison des pluies", "Uniquement en décembre", "Toute l'année"], correct: 0, explication: "Les cérémonies de circoncision kota se déroulent traditionnellement pendant la saison sèche, de juin à septembre." },
  { theme: "Culture", difficulte: "facile", question: "Chez les Kota, la cérémonie de circoncision est avant tout l'occasion de :", options: ["Marquer le passage à l'âge adulte et rassembler la famille élargie", "Une fête purement individuelle", "Un simple acte médical", "Une compétition sportive"], correct: 0, explication: "Au-delà de l'acte lui-même, la circoncision kota est un événement social majeur qui rassemble toute la famille élargie autour du passage à l'âge adulte." },
  { theme: "Culture", difficulte: "difficile", question: "Quelle langue parlent traditionnellement les Bakwélé, autre peuple présent dans l'Ogooué-Ivindo ?", options: ["Le bekwil (békwil)", "Le fang", "Le myéné", "Le lingala"], correct: 0, explication: "Les Bakwélé parlent traditionnellement le bekwil, une langue bantoue propre à leur communauté." },
  { theme: "Culture", difficulte: "moyen", question: "Parmi les peuples pygmées présents dans la province de l'Ogooué-Ivindo, lequel vit notamment autour de Mékambo ?", options: ["Les Bakoya", "Les Bedzan", "Les Twa", "Les San"], correct: 0, explication: "Les Bakoya, un peuple pygmée, vivent notamment autour de la région de Mékambo, dans l'Ogooué-Ivindo." },
  { theme: "Culture", difficulte: "difficile", question: "Les figures reliquaires mahongwé, avec leurs têtes distinctives, sont reconnaissables à quel style particulier ?", options: ["Un style \"foliacé\" (en forme de feuille)", "Un style rond et lisse", "Un style anguleux en cube", "Un style entièrement peint"], correct: 0, explication: "Les figures mahongwé se distinguent par un style dit \"foliacé\", avec des formes évoquant des feuilles, propres à ce sous-groupe kota." },
];

export default quizQuestions;
